# Generated by Django 2.1.7 on 2019-04-04 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CollegeEntityMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=10)),
                ('url', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('affiliation', models.ManyToManyField(blank=True, to='collegemodule.Affiliations')),
            ],
        ),
        migrations.CreateModel(
            name='CourseMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreferenceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=50, unique=True)),
                ('subCategory', models.CharField(blank=True, max_length=50, null=True)),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=30)),
                ('auth_token', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField()),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('registered_date', models.DateTimeField()),
                ('preferences', models.ManyToManyField(blank=True, to='collegemodule.PreferenceCategory')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='preferencecategory',
            unique_together={('categoryName', 'value')},
        ),
        migrations.AddField(
            model_name='affiliations',
            name='degree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collegemodule.CourseMaster'),
        ),
        migrations.AddField(
            model_name='affiliations',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collegemodule.University'),
        ),
        migrations.AlterUniqueTogether(
            name='affiliations',
            unique_together={('university', 'degree')},
        ),
    ]
