# Generated by Django 2.1.7 on 2019-03-31 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collegemodule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CollegeEntityMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=10)),
                ('url', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('affiliation', models.ManyToManyField(blank=True, to='collegemodule.Affiliations')),
            ],
        ),
        migrations.RemoveField(
            model_name='collegeentitymaser',
            name='affiliation',
        ),
        migrations.AlterField(
            model_name='coursemaster',
            name='degree',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='CollegeEntityMaser',
        ),
        migrations.AddField(
            model_name='affiliations',
            name='degree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collegemodule.CourseMaster'),
        ),
        migrations.AddField(
            model_name='affiliations',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collegemodule.University'),
        ),
        migrations.AlterUniqueTogether(
            name='affiliations',
            unique_together={('university', 'degree')},
        ),
    ]
